apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  serviceAccountName: jenkins-service-account
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ['${computer.jnlpmac}', '${computer.name}']
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - '--dockerfile=/workspace/Dockerfile'
        - '--context=/workspace/'
        - '--destination=${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}'
        - '--verbosity=debug'
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: workspace
          mountPath: /workspace
    - name: chronoscd
      image: lance0821/chronoscd:latest
      command: ['tail', '-f', '/dev/null'] # Keep the container alive
      tty: true
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-regcred
    - name: workspace
      emptyDir: {}
